name: Check Nix builds

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: nix flake check --no-build
        run: nix flake check --all-systems --no-build

  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - id: matrix
        name: Generate build matrix
        run: nix run .#gha-prepare-matrix

  build:
    needs:
      - eval
      - prepare-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: nixpkgs-ruby
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/checkout@v6
      - name: nix build check batch
        run: |
          installable='.#checkBatches.${{ matrix.system }}."${{ matrix.group }}".all'
          nix build --print-build-logs --keep-going "$installable"
